name: Default branch

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      # The semver tag, which is output only when the tagpr has tagged
      tag: ${{ steps.tagpr.outputs.tag }}
      # Information of the pull request created by tagpr in JSON format
      pull_request: ${{ steps.tagpr.outputs.pull_request }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.43.1
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
          cache: true
      - run: gh auth setup-git
        env:
          GH_HOST: github.com
      - id: tagpr
        run: tagpr
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ github.token }}

  release:
    needs: tagpr
    if: needs.tagpr.outputs.tag != ''
    uses: "./.github/workflows/wc-release.yml"
    permissions:
      contents: write
    with:
      tag: ${{ needs.tagpr.outputs.tag }}
    secrets:
      TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
