name: Manual release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  release:
    uses: "./.github/workflows/wc-release.yml"
    permissions:
      contents: write
    with:
      tag: ${{ github.ref_name }}
